# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  configuration: docs/rtd/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    post_install:
    - pip install --upgrade pip packaging wheel setuptools==69.5.1

python:
  install:
  - method: pip
    path: .
    extra_requirements:
      - docs
