name: Lint-black

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'


jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade packaging
        python -m pip show packaging
        make install-lint
    - name: Run black
      run: |
        make black-check
