name: Lint-flake8

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install-lint
    - name: Run flake8
      run: |
        make flake8
